language: java
git:
  depth: 1
jdk:
  - openjdk8
dist: trusty
cache:
  directories:
    - $HOME/.m2
#deploy:
#  provider: bluemixcloudfoundry
#  organization: cboudville@free.fr
#  space: dev
#  region: eu-gb
  
