language: java
php:
  - '5.5'
  - '5.6'
git:
  depth: 1
jdk:
  - openjdk8
dist: trusty
cache:
  directories:
    - $HOME/.m2
service:
  - mysql
install:
  - composer install
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS baladay;'  
  - mysql -u root --default-character-set=utf8 baladay < Schema.sql    
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  username: cboudville@free.fr
  password: $BLUEMIX_PASSWORD
  organization: cboudville@free.fr
  space: dev
  region: eu-gb

