= Dauphine Pole Info
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: dauphine-pole-info
:repository: Dauphine-Pole-Info

image:https://travis-ci.com/{gitHubUserName}/{repository}.svg?branch=master["Build Status", link="https://travis-ci.com/{gitHubUserName}/{repository}"]

A Java project developed during several sessions of the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] M2 MIAGE).

The code is hereby published under the MIT License, with the permission of the contributors.

== Doc
Installation de poleinfo3

Un serveur PHP et une base mySQL sont nécessaires : vous pouvez installer wamp,xamp ou mamp suivant votre OS.  
La démarche suivante a été réalisée avec wamp.  
  
1. Récupérer le code sur https://github.com/oliviercailloux/poleinfo3  
2. Déplacer le code dans le répertoire <www> de wamp  
3. Créer une base de données mySQL nommée "Master"  
  3.1 Soit en ligne de commande : mysqladmin -u root -p create Master  
  3.2 Soit avec phpMyAdmin  
4. Importer le fichier Schema.sql dans la base de données  
  4.1 ligne de commande : mysql -u root -p Master < Schema.sql
  4.2 ou avec phpMyAdmin
5. Indiquer les identifiants d'accès à la DB dans "DBinfo.php"
6. Activer les *short open tags* dans la configuration PHP
7. Accéder à l'application ! 
8. (Vous pouvez éventuellement réduire le niveau des erreurs rapportées pour ne pas prendre en compte les dépréciations)

== Template 

Ce projet utilise un template CRUD pour gérer l'objet master , (le lien de la template est ici : https://www.tutorialrepublic.com/snippets/preview.php?topic=bootstrap&file=crud-data-table-for-database-with-modal-form) - j'ai séparé le code html css et js parce qu'il était dans le meme fichier dans la template initiale-

template à ajouter (fait ?) : https://colorlib.com/wp/template/course/
